import Programs from './Programs';
// Autogenerated using npm run gen App
/*
 * Copy to other files
 * import App from './App';
 * <App/>
 */
import Error404 from './Error404';
import Header from './Header';
import Stats from './Stats';
import MatrixActions from './MatrixActions';
import styled from 'styled-components';
import Footer from './Footer';
import ShadowrunStore from './ShadowrunStore';
// import PropTypes from 'prop-types';
import { Switch, Route } from 'react-router-dom';

const defaultCyberdeckData = require('../test_data/cyberdecks.json');
const defaultMatrixActions = require('../data/matrixActions.json');

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      cyberdeckDataMaster: defaultCyberdeckData,
      matrixActions: defaultMatrixActions,
    };
    this.onHandleConfigStats = this.onHandleConfigStats.bind(this);
    this.onHandleProgramChange = this.onHandleProgramChange.bind(this);
  }

  onHandleConfigStats(name, value) {
    this.setState((state) => {
      const isAttribute = state.cyberdeckDataMaster.attributes[name];
      const stat = isAttribute
        ? state.cyberdeckDataMaster.attributes
        : state.cyberdeckDataMaster.skills;

      stat[name] = value;
      return { stat };
    });
  }

  onHandleProgramChange() {}

  componentDidMount() {}

  render() {
    const title = 'Shadowrun 5e Decker Edition';
    return (
      <Main className="container-fluid bg-dark">
        <HeaderStyle>
          <Header />
        </HeaderStyle>
        <Title className="jumbotron">{title}</Title>
        <Switch>
          <Route exact path="/" />
          <Route
            exact
            path="/cyberdeck"
            render={() => (
              <div>
                <ShadowrunStore></ShadowrunStore>
                <div className="d-flex flex-wrap justify-content-center">
                  <Stats
                    className=""
                    cyberdeckData={this.state.cyberdeckDataMaster}
                    handleConfigStats={this.onHandleConfigStats}
                  />
                  <Programs
                    className=""
                    cyberdeckData={this.state.cyberdeckDataMaster}
                    handleProgramChange={this.state.onHandleProgramChange}
                    handleConfigStats={this.onHandleConfigStats}
                  />
                </div>
                <div>
                  <MatrixActions
                    cyberdeckData={this.state.cyberdeckDataMaster}
                    matrixActions={this.state.matrixActions}
                  />
                </div>
              </div>
            )}
          />
          <Route component={Error404} />
        </Switch>
        <Footer />
      </Main>
    );
  }
}

/*
App.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default App;

const Main = styled.div`
  font-family: Open Sans;
`;

const Title = styled.h1`
  text-align: center;
  font-weight: 800;
`;

const HeaderStyle = styled.div`
  font-size: 1.5em;
  text-align: center;
`;
