// Autogenerated using npm run gen App
/*
 * Copy to other files
 * import App from './App';
 * <App/>
 */
import Error404 from './Error404';
import Header from './Header';
import Cyberdeck from './cyberdeck';
import MatrixActions from './MatrixActions';
import styled from 'styled-components';
import Footer from './Footer';
// import PropTypes from 'prop-types';
import { Switch, Route } from 'react-router-dom';

const defaultCyberdeckData = require('../test_data/cyberdecks.json');
const defaultMatrixActions = require('../data/matrixActions.json');

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      cyberdeckDataMaster: defaultCyberdeckData,
      matrixActions: defaultMatrixActions,
    };
    this.onHandleConfigAttributes = this.onHandleConfigAttributes.bind(this);
    this.onHandleConfigSkills = this.onHandleConfigSkills.bind(this);
  }

  onHandleConfigAttributes(attributeName, value) {
    this.setState((state) => {
      let attributes = state.cyberdeckDataMaster.attributes;
      attributes[attributeName] = value;
      return { player: attributes };
    });
  }

  onHandleConfigSkills(skillName, value) {
    this.setState((state) => {
      let skills = state.cyberdeckDataMaster.skills;
      skills[skillName] = value;
      return { player: skills };
    });
  }

  componentDidMount() {}

  render() {
    const title = 'Shadowrun 5e Decker Edition';
    return (
      <Main className="container-fluid bg-dark">
        <HeaderStyle>
          <Header />
        </HeaderStyle>
        <Title className="jumbotron">{title}</Title>
        <Switch>
          <Route exact path="/" />
          <Route
            exact
            path="/cyberdeck"
            render={() => (
              <div>
                <Cyberdeck
                  cyberdeckData={this.state.cyberdeckDataMaster}
                  handleConfigAttributes={this.onHandleConfigAttributes}
                  handleConfigSkills={this.onHandleConfigSkills}
                />
                <br />
                <MatrixActions
                  cyberdeckData={this.state.cyberdeckDataMaster}
                  matrixActions={this.state.matrixActions}
                />
              </div>
            )}
          />
          <Route component={Error404} />
        </Switch>
        <Footer />
      </Main>
    );
  }
}

/*
App.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default App;

const Main = styled.div`
  font-family: Open Sans;
`;

const Title = styled.h1`
  text-align: center;
  font-weight: 800;
`;

const HeaderStyle = styled.div`
  font-size: 1.5em;
  text-align: center;
`;
