// Autogenerated using npm run gen Character
/*
 * Copy to other files
 * import Character from './Character';
 * <Character/>
 */
import styled from 'styled-components';
// import PropTypes from 'prop-types';
// import { Link, Switch, Route } from 'react-router-dom';

function Character() {
  return (
    <Main>
      <h1>Lorem Ipsum</h1>
    </Main>
  );
}

/*
Character.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default Character;

const Main = styled.div`
  background-color: white;
  font-family: Courier New;
  color: black;
  font-weight: normal;
`;
