// Autogenerated using npm run gen Error404
/*
 * Copy to other files
 * import Error404 from './Error404';
 * <Error404/>
 */
import styled from 'styled-components';
// import PropTypes from 'prop-types';
// import { Link, Switch, Route } from 'react-router-dom';

function Error404() {
  return (
    <Main>
      <h1>Error 404</h1>
    </Main>
  );
}

/*
Error404.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default Error404;

const Main = styled.div`
  background-color: black;
  font-family: Open Sans;
  padding-top: 50px;
  color: white;
`;
