// Autogenerated using npm run gen Footer
/*
 * Copy to other files
 * import Footer from './Footer';
 * <Footer/>
 */
import styled from 'styled-components';
// import PropTypes from 'prop-types';
// import { Link, Switch, Route } from 'react-router-dom';

function Footer() {
  const toppsCopyright =
    'The Topps Company, Inc. has sole ownership of the names, logo, artwork, marks, photographs, sounds, audio, video and/or any proprietary material used in connection with the game Shadowrun. The Topps Company, Inc. has granted permission to < fill in the name of your site > to use such names, logos, artwork, marks and/or any proprietary materials for promotional and informational purposes on its website but does not endorse, and is not affiliated with < fill in the name of your site > in any official capacity whatsoever.';
  return (
    <Main className="container bg-secondary">
      <p>{toppsCopyright}</p>
    </Main>
  );
}

/*
Footer.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default Footer;

const Main = styled.div`
  font-family: sans-serif;
  padding-top: 10px;
`;
