// Autogenerated using npm run gen Header

import styled from 'styled-components';
import { Link } from 'react-router-dom';

function Header() {
  return (
    <Main className="bg-black text-info">
      <Link className="text-info" to="/">
        dev
      </Link>
      <span className="text-white">/</span>
      <Link className="text-info" to="/cyberdeck">
        cyberdeck
      </Link>
    </Main>
  );
}

export default Header;

const Main = styled.div`
  font-family: Open Sans;
  font-weight: 800;
`;
