// Autogenerated using npm run gen Matrix
import styled from 'styled-components';
import Stats from './Stats';
import MatrixActions from './MatrixActions';
import Programs from './Programs';

function Matrix() {
  return (
    <Main>
      <div className="d-flex flex-wrap justify-content-center">
        <Stats className="" />
        <Programs className="" />
      </div>
      <div>
        <MatrixActions />
      </div>
    </Main>
  );
}

export default Matrix;

const Main = styled.div``;
