/* eslint-disable react/prefer-stateless-function */
import Program from './Program';
// Autogenerated using npm run gen Programs
/*
 * Copy to other files
 * import Programs from './Programs';
 * <Programs/>
 */
import styled from 'styled-components';
import PropTypes from 'prop-types';
import ProgramData from '../data/programs.json';

class Programs extends React.Component {
  constructor(props) {
    super(props);
    this.state = { description: '' };
    this.handleButtonHover = this.handleButtonHover.bind(this);
  }

  handleButtonHover(description) {
    this.setState((state) => {
      state.description = description;
    });
  }

  render() {
    const sortedPrograms = ProgramData.sort((a, b) => {
      return a.name > b.name ? 1 : -1;
    });
    const Programs = sortedPrograms.map((program, key) => (
      <Program
        key={key}
        onHandleProgramChange={this.props.handleProgramChange}
        onHandleConfigStats={this.props.handleConfigStats}
        onHandleButtonHover={this.handleButtonHover}
        cyberdeckData={this.props.cyberdeckData}
        program={program}
      />
    ));
    return (
      <Main className="container">
        <div className="card bg-info">
          <Title className="card-header">Programs</Title>
          <div className="card-body">
            <div className="card-text">
              <div className="flex-wrap flex-align btn-group">{Programs}</div>
            </div>
            <div className="card-footer">
              Description: {this.state.description}
            </div>
          </div>
        </div>
      </Main>
    );
  }
}

Programs.propTypes = {
  cyberdeckData: PropTypes.object,
  handleProgramChange: PropTypes.func,
  handleConfigStats: PropTypes.func,
};

export default Programs;

const Main = styled.div`
  font-family: Open Sans;
  font-weight: normal;
`;

const Title = styled.h4`
  font-family: Open Sans;
  font-weight: normal;
  text-align: center;
`;
