/* eslint-disable react/prefer-stateless-function */
import Program from './Program';
// Autogenerated using npm run gen Programs
/*
 * Copy to other files
 * import Programs from './Programs';
 * <Programs/>
 */
import styled from 'styled-components';
import PropTypes from 'prop-types';
// import ProgramData from '../data/programs.json';

class Programs extends React.Component {
  constructor(props) {
    super(props);
    this.state = { description: '' };
    this.handleButtonHover = this.handleButtonHover.bind(this);
  }

  handleButtonHover(description) {
    this.setState((state) => {
      state.description = description;
    });
  }

  render() {
    return (
      <Main className="bg-info">
        <div>Description: {this.state.description}</div>
        <div className="d-flex">
          <Program
            onHandleProgramChange={this.props.handleProgramChange}
            onHandleConfigStats={this.props.handleConfigStats}
            onHandleButtonHover={this.handleButtonHover}
            cyberdeckData={this.props.cyberdeckData}
            name={'Decryption'}
          />
          <Program
            onHandleProgramChange={this.props.handleProgramChange}
            onHandleConfigStats={this.props.handleConfigStats}
            onHandleButtonHover={this.handleButtonHover}
            cyberdeckData={this.props.cyberdeckData}
            name={'Decryption'}
          />
        </div>
      </Main>
    );
  }
}

Programs.propTypes = {
  cyberdeckData: PropTypes.object,
  handleProgramChange: PropTypes.func,
  handleConfigStats: PropTypes.func,
};

export default Programs;

const Main = styled.div`
  font-family: Open Sans;
  font-weight: normal;
`;
