/* Autogenerated using npm run gen Program
 *
 * Copy to other files
 * import Program from './Program';
 * <Program/>
 */
import styled from 'styled-components';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { setProgramDescription } from '../data/actions.js';

class Program extends React.Component {
  constructor(props) {
    super(props);

    this.state = { count: 0 };
    this.handleAddCountValue = this.handleAddCountValue.bind(this);
  }

  handleAddCountValue(value) {
    this.setState((state) => {
      state.count += value;
    });
  }

  handleButtonClick() {
    const program = this.props.program;
    const max = program.max;
    const increment = program.increment;
    const value = this.state.count >= max ? -max : increment;
    console.log(value);
    this.handleAddCountValue(value);
    const name = program.modify;
    // this.props.onHandleConfigStats(
    //   name,
    //   this.props.cyberdeckData.attributes[name] + value
    // );
  }

  handleButtonOver() {
    this.props.setProgramDescription(this.props.program.description);
  }

  handleButtonOut() {
    this.props.setProgramDescription('');
  }

  render() {
    const currentClass =
      this.state.count <= 0 ? 'btn btn-light' : 'btn btn-success';
    return (
      <Main classname="">
        <div>
          <button
            className={currentClass}
            onClick={() => this.handleButtonClick()}
            onMouseOver={() => this.handleButtonOver()}
            onMouseOut={() => this.handleButtonOut()}>
            {this.props.program.name}
          </button>
        </div>
      </Main>
    );
  }
}

Program.propTypes = {
  setProgramDescription: PropTypes.func,
  program: PropTypes.object,
};

function mapStateToProps(state) {
  return {
    programDescription: state.programDescription,
  };
}

const mapDispatchToProps = {
  setProgramDescription,
};

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Program);

const Main = styled.div`
  font-family: Open Sans;
  font-weight: normal;
  margin: 3px;
`;
