/* eslint-disable react/prefer-stateless-function */
import Program from './Program';
// Autogenerated using npm run gen Programs
/*
 * Copy to other files
 * import Programs from './Programs';
 * <Programs/>
 */
import { connect } from 'react-redux';
import styled from 'styled-components';
import PropTypes from 'prop-types';
import ProgramData from '../data/programs.json';

class Programs extends React.Component {
  render() {
    const sortedPrograms = ProgramData.sort((a, b) => {
      return a.name > b.name ? 1 : -1;
    });
    const Programs = sortedPrograms.map((program, key) => (
      <Program
        key={key}
        onHandleProgramChange={this.props.handleProgramChange}
        onHandleConfigStats={this.props.handleConfigStats}
        cyberdeckData={this.props.cyberdeckData}
        program={program}
      />
    ));
    return (
      <Main className="container">
        <div className="card bg-info">
          <Title className="card-header">Programs</Title>
          <div className="card-body">
            <div className="card-text">
              <div className="flex-wrap flex-align btn-group">{Programs}</div>
            </div>
            <div className="card-footer">
              Description: {this.props.programDescription}
            </div>
          </div>
        </div>
      </Main>
    );
  }
}

Programs.propTypes = {
  cyberdeckData: PropTypes.object,
  handleProgramChange: PropTypes.func,
  handleConfigStats: PropTypes.func,
  programDescription: PropTypes.string,
};

function mapStateToProps(state) {
  return {
    programDescription: state.programDescription,
  };
}

const mapDispatchToProps = {};

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Programs);

const Main = styled.div`
  font-family: Open Sans;
  font-weight: normal;
`;

const Title = styled.h4`
  font-family: Open Sans;
  font-weight: normal;
  text-align: center;
`;
