/* eslint-disable react/prop-types */
/* eslint-disable react/jsx-handler-names */
// Autogenerated using npm run gen ShadowrunStore
/*
 * Copy to other files
 * import ShadowrunStore from './ShadowrunStore';
 * <ShadowrunStore/>
 */
import { connect } from 'react-redux';
import styled from 'styled-components';
import { increment, decrement } from '../data/actions.js';

class ShadowrunStore extends React.Component {
  increment() {
    this.props.increment();
  }

  decrement() {
    this.props.decrement();
  }

  render() {
    return (
      <Main>
        <h2>ShadowrunStore</h2>
        <div>
          <button onClick={() => this.decrement()}>-</button>
          <div>{this.props.count}</div>
          <button onClick={() => this.increment()}>+</button>
        </div>
      </Main>
    );
  }
}

ShadowrunStore.propTypes = {
  count: PropTypes.number,
};

function mapStateToProps(state) {
  return {
    count: state.count,
  };
}

const mapDispatchToProps = {
  increment,
  decrement,
};

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(ShadowrunStore);

const Main = styled.div`
  background-color: white;
  font-family: Courier New;
  color: black;
  font-weight: normal;
`;
