// Autogenerated using npm run gen Skills
/*
 * Copy to other files
 * import Skills from './Skills';
 * <Skills/>
 */
import styled from 'styled-components';
// import PropTypes from 'prop-types';
// import { Link, Switch, Route } from 'react-router-dom';

function Skills() {
  return (
    <Main>
      <h1>Lorem Ipsum</h1>
    </Main>
  );
}

/*
Skills.propTypes = {
  //  [variable-name]: PropTypes.[type],
};
*/

export default Skills;

const Main = styled.div`
  background-color: white;
  font-family: Courier New;
  color: black;
  font-weight: normal;
`;
