// Autogenerated using npm run gen Stat
/*
 * Copy to other files
 * import Stat from './Stat';
 * <Stat/>
 */
import styled from 'styled-components';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import {
  setSkill,
  setAttribute,
  setDeckingDeviceStat,
} from '../data/actions.js';

class Stat extends React.Component {
  constructor(props) {
    super(props);
  }

  handleStatChange(event) {
    const text = this.props.name;
    const newValue = parseInt(event.target.value);
    switch (this.props.actionType) {
      case 'SETSKILL':
        this.props.setSkill(text, newValue);
        break;
      case 'SETATTRIBUTE':
        this.props.setAttribute(text, newValue);
        break;
      case 'SETDECKINGDEVICESTAT':
        this.props.setDeckingDeviceStat(text, newValue);
        break;
    }
  }

  render() {
    return (
      <Main className="">
        <CardStyle className="card bg-info">
          <TitleHeader className="card-header">{this.props.title}</TitleHeader>
          <div className="card-body">
            <div className="card-text">
              <label>
                <Input
                  key={1}
                  name={this.props.name}
                  type="number"
                  onChange={(event) => this.handleStatChange(event)}
                  value={this.props.value}
                />
              </label>
            </div>
          </div>
        </CardStyle>
      </Main>
    );
  }
}

Stat.propTypes = {
  name: PropTypes.string,
  setSkill: PropTypes.func,
  setAttribute: PropTypes.func,
  setDeckingDeviceStat: PropTypes.func,
  title: PropTypes.string,
  actionType: PropTypes.string,
  value: PropTypes.number,
};

function mapStateToProps() {
  return {};
}

const mapDispatchToProps = {
  setSkill,
  setAttribute,
  setDeckingDeviceStat,
};

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Stat);

const Main = styled.div`
  font-family: Open Sans;
  color: black;
  font-weight: normal;
  font-size: 1em;
`;

const Input = styled.input`
  font-family: Open Sans;
  color: black;
  font-size: 1em;
  width: 100px;
  text-align: center;
`;

const CardStyle = styled.div`
  width: 250px;
  font-size: 0.8em;
  text-align: center;
`;

const TitleHeader = styled.div`
  font-size: 1.5em;
`;
