// Autogenerated using npm run gen cyberdeck
/*
 * Copy to other files
 * import cyberdeck from './cyberdeck';
 * <cyberdeck/>
 */
import styled from 'styled-components';
import PropTypes from 'prop-types';
import Stat from './Stat';

function Stats(props) {
  // console.log(this.props.cyberdeckData);
  return (
    <Main className="">
      <div className="d-flex justify-content-center">
        <Stat
          name={'attack'}
          title={'Attack'}
          value={props.cyberdeckData.attributes.attack}
          onHandleConfigStats={props.handleConfigStats}
        />
        <Stat
          name={'sleaze'}
          title={'Sleaze'}
          value={props.cyberdeckData.attributes.sleaze}
          onHandleConfigStats={props.handleConfigStats}
        />
        <Stat
          name={'dataProcessing'}
          title={'Data Processing'}
          value={props.cyberdeckData.attributes.dataProcessing}
          onHandleConfigStats={props.handleConfigStats}
        />
        <Stat
          name={'firewall'}
          title={'Firewall'}
          value={props.cyberdeckData.attributes.firewall}
          onHandleConfigStats={props.handleConfigStats}
        />
      </div>
      <div className="d-flex justify-content-center">
        <Stat
          name={'logic'}
          title={'Logic'}
          value={props.cyberdeckData.attributes.logic}
          onHandleConfigStats={props.handleConfigStats}
        />
        <Stat
          name={'intuition'}
          title={'Intuition'}
          value={props.cyberdeckData.attributes.intuition}
          onHandleConfigStats={props.handleConfigStats}
        />
        <Stat
          name={'willpower'}
          title={'Willpower'}
          value={props.cyberdeckData.attributes.willpower}
          onHandleConfigStats={props.handleConfigStats}
        />
        <Stat
          name={'reaction'}
          title={'Reaction'}
          value={props.cyberdeckData.attributes.reaction}
          onHandleConfigStats={props.handleConfigStats}
        />
      </div>
      <div className="d-flex justify-content-center">
        <Stat
          name={'computer'}
          title={'Computer'}
          value={props.cyberdeckData.skills.computer}
          onHandleConfigStats={props.handleConfigStats}
        />
        <Stat
          name={'cybercombat'}
          title={'Cybercombat'}
          value={props.cyberdeckData.skills.cybercombat}
          onHandleConfigStats={props.handleConfigStats}
        />
        <Stat
          name={'electronicWarfare'}
          title={'Electronic Warfare'}
          value={props.cyberdeckData.skills.electronicWarfare}
          onHandleConfigStats={props.handleConfigStats}
        />
        <Stat
          name={'hacking'}
          title={'Hacking'}
          value={props.cyberdeckData.skills.hacking}
          onHandleConfigStats={props.handleConfigStats}
        />
        <Stat
          name={'hardware'}
          title={'Hardware'}
          value={props.cyberdeckData.skills.hardware}
          onHandleConfigStats={props.handleConfigStats}
        />
        <Stat
          name={'software'}
          title={'Software'}
          value={props.cyberdeckData.skills.software}
          onHandleConfigStats={props.handleConfigStats}
        />
      </div>
    </Main>
  );
}

Stats.propTypes = {
  cyberdeckData: PropTypes.object,
  handleConfigStats: PropTypes.func,
};

export default Stats;

const Main = styled.div`
  font-family: Open Sans;
  color: black;
  font-size: 1em;
`;
