// Autogenerated using npm run gen Stat
/*
 * Copy to other files
 * import Stat from './Stat';
 * <Stat/>
 */
import styled from 'styled-components';
import PropTypes from 'prop-types';

class Stat extends React.Component {
  constructor(props) {
    super(props);
    this.handleStatChange = this.handleStatChange.bind(this);
  }
  handleStatChange(event) {
    const name = event.target.getAttribute('name');
    const newValue = parseInt(event.target.value);
    this.props.onHandleConfigStats(name, newValue);
  }
  render() {
    return (
      <Main>
        <CardStyle className="card">
          <div className="card-body">
            <TitleHeader className="card-title">{this.props.title}</TitleHeader>
            <div className="card-text">
              <Input
                name={this.props.name}
                type="number"
                value={this.props.value}
                onChange={this.handleStatChange}
              />
            </div>
          </div>
        </CardStyle>
      </Main>
    );
  }
}

Stat.propTypes = {
  name: PropTypes.string,
  value: PropTypes.number,
  onHandleConfigStats: PropTypes.func,
  title: PropTypes.string,
};

export default Stat;

const Main = styled.div`
  font-family: Open Sans;
  color: black;
  font-weight: normal;
  font-size: 1em;
`;

const Input = styled.input`
  font-family: Open Sans;
  color: black;
  font-size: 1em;
  width: 100px;
  text-align: center;
`;

const CardStyle = styled.div`
  width: 250px;
  font-size: 0.8em;
  text-align: center;
`;

const TitleHeader = styled.div`
  font-size: 1.5em;
`;
