// Autogenerated using npm run gen cyberdeck
/*
 * Copy to other files
 * import cyberdeck from './cyberdeck';
 * <cyberdeck/>
 */
import styled from 'styled-components';
import PropTypes from 'prop-types';
import Stat from './Stat';
import { connect } from 'react-redux';

class Stats extends React.Component {
  constructor(props) {
    super(props);
  }
  listDeckAttribs = () => {
    const deckingStats = ['Attack', 'Sleaze', 'Data Processing', 'Firewall','Pilot','Agent'];
    const renderStats = [];
    deckingStats.forEach((stat, index) => {
      const statLowerCase = stat.toLowerCase();
      renderStats.push(
        <Stat
          key={index}
          name={statLowerCase}
          title={stat}
          actionType={'SETDECKINGDEVICESTAT'}
          value={this.props.deckingDevice.attributes[statLowerCase].ranks}
        />
      );
    });
    return renderStats;
  };

  listCharAttribs = () => {
    const attributes = ['Logic', 'Intuition', 'Willpower', 'Reaction'];
    const renderStats = [];
    attributes.forEach((stat, index) => {
      const statLowerCase = stat.toLowerCase();
      renderStats.push(
        <Stat
          key={index}
          name={statLowerCase}
          title={stat}
          actionType={'SETATTRIBUTE'}
          value={this.props.attributes[statLowerCase].ranks}
        />
      );
    });
    return renderStats;
  };

  listSkillStats = () => {
    const skillStats = [
      'Computer',
      'Cybercombat',
      'Electronic Warfare',
      'Hacking',
      'Hardware',
      'Software',
    ];
    const renderStats = [];
    skillStats.forEach((stat, index) => {
      const skillLowerCase = stat.toLowerCase();
      renderStats.push(
        <Stat
          key={index}
          name={skillLowerCase}
          title={stat}
          actionType={'SETSKILL'}
          value={this.props.skills[skillLowerCase].ranks}
        />
      );
    });
    return renderStats;
  };

  render() {
    return (
      <Main className="">
        <div className="d-flex justify-content-center">
          {this.listDeckAttribs()}
        </div>
        <div className="d-flex justify-content-center">
          {this.listCharAttribs()}
        </div>
        <div className="d-flex justify-content-center">
          {this.listSkillStats()}
        </div>
      </Main>
    );
  }
}

Stats.propTypes = {
  attributes: PropTypes.object,
  skills: PropTypes.object,
  deckingDevice: PropTypes.object,
};

function mapStateToProps(state) {
  return {
    attributes: state.attributes,
    skills: state.skills,
    deckingDevice: state.deckingDevice,
  };
}

const mapDispatchToProps = {};

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Stats);

const Main = styled.div`
  font-family: Open Sans;
  color: black;
  font-size: 1em;
`;
